homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Paris
  customize: !include_dir_merge_named customizations

# introduction:
# discovery:
# map:
# cloud:
config:
conversation:
hassio:
frontend:
recorder:
history:
ios:
logbook:
sun:
updater:
  include_used_components: true

automation: !include_dir_merge_list automations
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
device_tracker: !include device_tracker.yaml
group: !include_dir_merge_named groups
google_assistant: !include google_assistant.yaml
history_graph: !include history_graph.yaml
homekit: !include homekit.yaml
http: !include http.yaml
logger: !include logger.yaml
cast: !include cast.yaml
mqtt: !include mqtt.yaml
notify: !include notify.yaml
scene: !include_dir_merge_list scenes
script: !include scripts.yaml
sensor: !include sensor.yaml
zone: !include_dir_merge_list zones

zwave:
  usb_path: /dev/ttyAMA0
  network_key: !secret zwave_network_key

tts:
  - platform: google
  
hue:
  bridges:
    - host: !secret ip_philips_hue_bridge
      filename: phue.conf

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

ifttt:
  key: !secret ifttt_key

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - host: !secret ip_xiaomi_gateway
      key: !secret xiaomi_gateway_key


# panel_iframe:
#   configurator:
#     title: Configurator
#     icon: mdi:wrench
#     url: https://hassio.local:3218

