homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Paris
  customize: !include_dir_merge_named customizations

# introduction:
discovery:
frontend:
config:
conversation:
history:
logbook:
map:
sun:
cloud:
updater:

automation: !include_dir_merge_list automations
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
device_tracker: !include device_tracker.yaml
http: !include http.yaml
logger: !include logger.yaml
media_player: !include media_player.yaml
mqtt: !include mqtt.yaml
notify: !include notify.yaml
group: !include_dir_merge_named groups
scene: !include_dir_merge_list scenes
script: !include scripts.yaml
sensor: !include sensor.yaml
zone: !include_dir_merge_list zones

zwave:
  usb_path: /dev/ttyAMA0
  network_key: !secret zwave_network_key

tts:
  - platform: google
  
hue:
  bridges:
    - host: !secret ip_philips_hue_bridge
      filename: phue.conf

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

ifttt:
  key: !secret ifttt_key

# panel_iframe:
#   configurator:
#     title: Configurator
#     icon: mdi:wrench
#     url: https://hassio.local:3218

# google_assistant:
#   project_id: !secret ga_project_id
#   client_id: !secret ga_client_id
#   access_token: !secret ga_access_token
#   agent_user_id: !secret ga_agent_user_id
#   api_key: !secret ga_api_key
#   exposed_domains:
#     - switch
#     - light
#     - group