- platform: hue

- platform: speedtest
  minute:
    - 0
    - 30
  monitored_conditions:
    - ping
    - download
    - upload

- platform: openweathermap
  api_key: !secret openweathermap_key
  language: fr
  monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - humidity
      - pressure
      - clouds
      - rain
      - snow

- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: load_1m
  - type: load_5m
  - type: load_15m
  - type: memory_free
  - type: memory_use
  - type: processor_use
  - type: network_in
    arg: eth0
  - type: network_out
    arg: eth0
  - type: ipv4_address
    arg: eth0
  - type: last_boot

- platform: fitbit
  clock_format: 24H
  monitored_resources:
    - "activities/activityCalories"
    - "activities/calories"
    - "activities/caloriesBMR"
    - "activities/distance"
    - "activities/elevation"
    - "activities/floors"
    - "activities/heart"
    - "activities/minutesFairlyActive"
    - "activities/minutesLightlyActive"
    - "activities/minutesSedentary"
    - "activities/minutesVeryActive"
    - "activities/steps"
    - "activities/tracker/activityCalories"
    - "activities/tracker/calories"
    - "activities/tracker/distance"
    - "activities/tracker/elevation"
    - "activities/tracker/floors"
    - "activities/tracker/minutesFairlyActive"
    - "activities/tracker/minutesLightlyActive"
    - "activities/tracker/minutesSedentary"
    - "activities/tracker/minutesVeryActive"
    - "activities/tracker/steps"
    - "body/bmi"
    - "body/fat"
    - "body/weight"
    - "devices/battery"
    - "sleep/awakeningsCount"
    - "sleep/efficiency"
    - "sleep/minutesAfterWakeup"
    - "sleep/minutesAsleep"
    - "sleep/minutesAwake"
    - "sleep/minutesToFallAsleep"
    - "sleep/startTime"
    - "sleep/timeInBed"


- platform: template
  sensors:
    ## Bateries
    xiaomi_158d000223a2af_battery:
      friendly_name: "Battery Desk Temp"
      value_template: >-
        {%- if states.sensor.temperature_158d000223a2af -%}
          {{ states.sensor.temperature_158d000223a2af.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      icon_template: >-
        {% if states.sensor.temperature_158d000223a2af.attributes.battery_level <= 10 %}
          mdi:battery-10
        {% elif states.sensor.temperature_158d000223a2af.attributes.battery_level <= 20 %}
          mdi:battery-20
        {% elif states.sensor.temperature_158d000223a2af.attributes.battery_level <= 30 %}
          mdi:battery-30
        {% elif states.sensor.temperature_158d000223a2af.attributes.battery_level <= 40 %}
          mdi:battery-40
        {% elif states.sensor.temperature_158d000223a2af.attributes.battery_level <= 50 %}
          mdi:battery-50
        {% elif states.sensor.temperature_158d000223a2af.attributes.battery_level <= 60 %}
          mdi:battery-60
        {% elif states.sensor.temperature_158d000223a2af.attributes.battery_level <= 70 %}
          mdi:battery-70
        {% elif states.sensor.temperature_158d000223a2af.attributes.battery_level <= 80 %}
          mdi:battery-80
        {% elif states.sensor.temperature_158d000223a2af.attributes.battery_level <= 90 %}
          mdi:battery-90
        {% else %}
          mdi:battery
        {% endif %}
    xiaomi_158d000227cc0b_battery:
      friendly_name: "Battery Bedroom Temp"
      value_template: >-
        {%- if states.sensor.temperature_158d000227cc0b -%}
          {{ states.sensor.temperature_158d000227cc0b.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      icon_template: >-
        {% if states.sensor.temperature_158d000227cc0b.attributes.battery_level <= 10 %}
          mdi:battery-10
        {% elif states.sensor.temperature_158d000227cc0b.attributes.battery_level <= 20 %}
          mdi:battery-20
        {% elif states.sensor.temperature_158d000227cc0b.attributes.battery_level <= 30 %}
          mdi:battery-30
        {% elif states.sensor.temperature_158d000227cc0b.attributes.battery_level <= 40 %}
          mdi:battery-40
        {% elif states.sensor.temperature_158d000227cc0b.attributes.battery_level <= 50 %}
          mdi:battery-50
        {% elif states.sensor.temperature_158d000227cc0b.attributes.battery_level <= 60 %}
          mdi:battery-60
        {% elif states.sensor.temperature_158d000227cc0b.attributes.battery_level <= 70 %}
          mdi:battery-70
        {% elif states.sensor.temperature_158d000227cc0b.attributes.battery_level <= 80 %}
          mdi:battery-80
        {% elif states.sensor.temperature_158d000227cc0b.attributes.battery_level <= 90 %}
          mdi:battery-90
        {% else %}
          mdi:battery
        {% endif %}
    xiaomi_158d0002271a4a_battery:
      friendly_name: "Battery Bathroom Temp"
      value_template: >-
        {%- if states.sensor.temperature_158d0002271a4a -%}
          {{ states.sensor.temperature_158d0002271a4a.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      icon_template: >-
        {% if states.sensor.temperature_158d0002271a4a.attributes.battery_level <= 10 %}
          mdi:battery-10
        {% elif states.sensor.temperature_158d0002271a4a.attributes.battery_level <= 20 %}
          mdi:battery-20
        {% elif states.sensor.temperature_158d0002271a4a.attributes.battery_level <= 30 %}
          mdi:battery-30
        {% elif states.sensor.temperature_158d0002271a4a.attributes.battery_level <= 40 %}
          mdi:battery-40
        {% elif states.sensor.temperature_158d0002271a4a.attributes.battery_level <= 50 %}
          mdi:battery-50
        {% elif states.sensor.temperature_158d0002271a4a.attributes.battery_level <= 60 %}
          mdi:battery-60
        {% elif states.sensor.temperature_158d0002271a4a.attributes.battery_level <= 70 %}
          mdi:battery-70
        {% elif states.sensor.temperature_158d0002271a4a.attributes.battery_level <= 80 %}
          mdi:battery-80
        {% elif states.sensor.temperature_158d0002271a4a.attributes.battery_level <= 90 %}
          mdi:battery-90
        {% else %}
          mdi:battery
        {% endif %}
    xiaomi_158d0002272d57_battery:
      friendly_name: "Battery Kitchen Temp"
      value_template: >-
        {%- if states.sensor.temperature_158d0002272d57 -%}
          {{ states.sensor.temperature_158d0002272d57.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      icon_template: >-
        {% if states.sensor.temperature_158d0002272d57.attributes.battery_level <= 10 %}
          mdi:battery-10
        {% elif states.sensor.temperature_158d0002272d57.attributes.battery_level <= 20 %}
          mdi:battery-20
        {% elif states.sensor.temperature_158d0002272d57.attributes.battery_level <= 30 %}
          mdi:battery-30
        {% elif states.sensor.temperature_158d0002272d57.attributes.battery_level <= 40 %}
          mdi:battery-40
        {% elif states.sensor.temperature_158d0002272d57.attributes.battery_level <= 50 %}
          mdi:battery-50
        {% elif states.sensor.temperature_158d0002272d57.attributes.battery_level <= 60 %}
          mdi:battery-60
        {% elif states.sensor.temperature_158d0002272d57.attributes.battery_level <= 70 %}
          mdi:battery-70
        {% elif states.sensor.temperature_158d0002272d57.attributes.battery_level <= 80 %}
          mdi:battery-80
        {% elif states.sensor.temperature_158d0002272d57.attributes.battery_level <= 90 %}
          mdi:battery-90
        {% else %}
          mdi:battery
        {% endif %}
    xiaomi_158d0002288280_battery:
      friendly_name: "Battery Bedroom 2 Temp"
      value_template: >-
        {%- if states.sensor.temperature_158d0002288280 -%}
          {{ states.sensor.temperature_158d0002288280.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      icon_template: >-
        {% if states.sensor.temperature_158d0002288280.attributes.battery_level <= 10 %}
          mdi:battery-10
        {% elif states.sensor.temperature_158d0002288280.attributes.battery_level <= 20 %}
          mdi:battery-20
        {% elif states.sensor.temperature_158d0002288280.attributes.battery_level <= 30 %}
          mdi:battery-30
        {% elif states.sensor.temperature_158d0002288280.attributes.battery_level <= 40 %}
          mdi:battery-40
        {% elif states.sensor.temperature_158d0002288280.attributes.battery_level <= 50 %}
          mdi:battery-50
        {% elif states.sensor.temperature_158d0002288280.attributes.battery_level <= 60 %}
          mdi:battery-60
        {% elif states.sensor.temperature_158d0002288280.attributes.battery_level <= 70 %}
          mdi:battery-70
        {% elif states.sensor.temperature_158d0002288280.attributes.battery_level <= 80 %}
          mdi:battery-80
        {% elif states.sensor.temperature_158d0002288280.attributes.battery_level <= 90 %}
          mdi:battery-90
        {% else %}
          mdi:battery
        {% endif %}
    xiaomi_158d0001b91beb_battery:
      friendly_name: "Battery Exterior Door"
      value_template: >-
        {%- if states.binary_sensor.door_window_sensor_158d0001b91beb -%}
          {{ states.binary_sensor.door_window_sensor_158d0001b91beb.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      icon_template: >-
        {% if states.binary_sensor.door_window_sensor_158d0001b91beb.attributes.battery_level <= 10 %}
          mdi:battery-10
        {% elif states.binary_sensor.door_window_sensor_158d0001b91beb.attributes.battery_level <= 20 %}
          mdi:battery-20
        {% elif states.binary_sensor.door_window_sensor_158d0001b91beb.attributes.battery_level <= 30 %}
          mdi:battery-30
        {% elif states.binary_sensor.door_window_sensor_158d0001b91beb.attributes.battery_level <= 40 %}
          mdi:battery-40
        {% elif states.binary_sensor.door_window_sensor_158d0001b91beb.attributes.battery_level <= 50 %}
          mdi:battery-50
        {% elif states.binary_sensor.door_window_sensor_158d0001b91beb.attributes.battery_level <= 60 %}
          mdi:battery-60
        {% elif states.binary_sensor.door_window_sensor_158d0001b91beb.attributes.battery_level <= 70 %}
          mdi:battery-70
        {% elif states.binary_sensor.door_window_sensor_158d0001b91beb.attributes.battery_level <= 80 %}
          mdi:battery-80
        {% elif states.binary_sensor.door_window_sensor_158d0001b91beb.attributes.battery_level <= 90 %}
          mdi:battery-90
        {% else %}
          mdi:battery
        {% endif %}
    xiaomi_158d0001debb0d_battery:
      friendly_name: "Battery Front Door"
      value_template: >-
        {%- if states.binary_sensor.door_window_sensor_158d0001debb0d -%}
          {{ states.binary_sensor.door_window_sensor_158d0001debb0d.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      icon_template: >-
        {% if states.binary_sensor.door_window_sensor_158d0001debb0d.attributes.battery_level <= 10 %}
          mdi:battery-10
        {% elif states.binary_sensor.door_window_sensor_158d0001debb0d.attributes.battery_level <= 20 %}
          mdi:battery-20
        {% elif states.binary_sensor.door_window_sensor_158d0001debb0d.attributes.battery_level <= 30 %}
          mdi:battery-30
        {% elif states.binary_sensor.door_window_sensor_158d0001debb0d.attributes.battery_level <= 40 %}
          mdi:battery-40
        {% elif states.binary_sensor.door_window_sensor_158d0001debb0d.attributes.battery_level <= 50 %}
          mdi:battery-50
        {% elif states.binary_sensor.door_window_sensor_158d0001debb0d.attributes.battery_level <= 60 %}
          mdi:battery-60
        {% elif states.binary_sensor.door_window_sensor_158d0001debb0d.attributes.battery_level <= 70 %}
          mdi:battery-70
        {% elif states.binary_sensor.door_window_sensor_158d0001debb0d.attributes.battery_level <= 80 %}
          mdi:battery-80
        {% elif states.binary_sensor.door_window_sensor_158d0001debb0d.attributes.battery_level <= 90 %}
          mdi:battery-90
        {% else %}
          mdi:battery
        {% endif %}
    xiaomi_158d0002135a1d_battery:
      friendly_name: "Battery Switch 1"
      value_template: >-
        {%- if states.binary_sensor.switch_158d0002135a1d -%}
          {{ states.binary_sensor.switch_158d0002135a1d.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      icon_template: >-
        {% if states.binary_sensor.switch_158d0002135a1d.attributes.battery_level <= 10 %}
          mdi:battery-10
        {% elif states.binary_sensor.switch_158d0002135a1d.attributes.battery_level <= 20 %}
          mdi:battery-20
        {% elif states.binary_sensor.switch_158d0002135a1d.attributes.battery_level <= 30 %}
          mdi:battery-30
        {% elif states.binary_sensor.switch_158d0002135a1d.attributes.battery_level <= 40 %}
          mdi:battery-40
        {% elif states.binary_sensor.switch_158d0002135a1d.attributes.battery_level <= 50 %}
          mdi:battery-50
        {% elif states.binary_sensor.switch_158d0002135a1d.attributes.battery_level <= 60 %}
          mdi:battery-60
        {% elif states.binary_sensor.switch_158d0002135a1d.attributes.battery_level <= 70 %}
          mdi:battery-70
        {% elif states.binary_sensor.switch_158d0002135a1d.attributes.battery_level <= 80 %}
          mdi:battery-80
        {% elif states.binary_sensor.switch_158d0002135a1d.attributes.battery_level <= 90 %}
          mdi:battery-90
        {% else %}
          mdi:battery
        {% endif %}
    xiaomi_158d0002133dfe_battery:
      friendly_name: "Battery Switch 2"
      value_template: >-
        {%- if states.binary_sensor.switch_158d0002133dfe -%}
          {{ states.binary_sensor.switch_158d0002133dfe.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      icon_template: >-
        {% if states.binary_sensor.switch_158d0002133dfe.attributes.battery_level <= 10 %}
          mdi:battery-10
        {% elif states.binary_sensor.switch_158d0002133dfe.attributes.battery_level <= 20 %}
          mdi:battery-20
        {% elif states.binary_sensor.switch_158d0002133dfe.attributes.battery_level <= 30 %}
          mdi:battery-30
        {% elif states.binary_sensor.switch_158d0002133dfe.attributes.battery_level <= 40 %}
          mdi:battery-40
        {% elif states.binary_sensor.switch_158d0002133dfe.attributes.battery_level <= 50 %}
          mdi:battery-50
        {% elif states.binary_sensor.switch_158d0002133dfe.attributes.battery_level <= 60 %}
          mdi:battery-60
        {% elif states.binary_sensor.switch_158d0002133dfe.attributes.battery_level <= 70 %}
          mdi:battery-70
        {% elif states.binary_sensor.switch_158d0002133dfe.attributes.battery_level <= 80 %}
          mdi:battery-80
        {% elif states.binary_sensor.switch_158d0002133dfe.attributes.battery_level <= 90 %}
          mdi:battery-90
        {% else %}
          mdi:battery
        {% endif %}
    xiaomi_158d0002135ac2_battery:
      friendly_name: "Battery Switch 3"
      value_template: >-
        {%- if states.binary_sensor.switch_158d0002135ac2 -%}
          {{ states.binary_sensor.switch_158d0002135ac2.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      icon_template: >-
        {% if states.binary_sensor.switch_158d0002135ac2.attributes.battery_level <= 10 %}
          mdi:battery-10
        {% elif states.binary_sensor.switch_158d0002135ac2.attributes.battery_level <= 20 %}
          mdi:battery-20
        {% elif states.binary_sensor.switch_158d0002135ac2.attributes.battery_level <= 30 %}
          mdi:battery-30
        {% elif states.binary_sensor.switch_158d0002135ac2.attributes.battery_level <= 40 %}
          mdi:battery-40
        {% elif states.binary_sensor.switch_158d0002135ac2.attributes.battery_level <= 50 %}
          mdi:battery-50
        {% elif states.binary_sensor.switch_158d0002135ac2.attributes.battery_level <= 60 %}
          mdi:battery-60
        {% elif states.binary_sensor.switch_158d0002135ac2.attributes.battery_level <= 70 %}
          mdi:battery-70
        {% elif states.binary_sensor.switch_158d0002135ac2.attributes.battery_level <= 80 %}
          mdi:battery-80
        {% elif states.binary_sensor.switch_158d0002135ac2.attributes.battery_level <= 90 %}
          mdi:battery-90
        {% else %}
          mdi:battery
        {% endif %}
    phue_hue_dimmer_switch_1_battery:
      friendly_name: "Hue dimmer switch 1"
      value_template: >-
        {%- if states.sensor.hue_dimmer_switch_1 -%}
          {{ states.sensor.hue_dimmer_switch_1.attributes.battery }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      icon_template: >-
        {% if states.sensor.hue_dimmer_switch_1.attributes.battery <= 10 %}
          mdi:battery-10
        {% elif states.sensor.hue_dimmer_switch_1.attributes.battery <= 20 %}
          mdi:battery-20
        {% elif states.sensor.hue_dimmer_switch_1.attributes.battery <= 30 %}
          mdi:battery-30
        {% elif states.sensor.hue_dimmer_switch_1.attributes.battery <= 40 %}
          mdi:battery-40
        {% elif states.sensor.hue_dimmer_switch_1.attributes.battery <= 50 %}
          mdi:battery-50
        {% elif states.sensor.hue_dimmer_switch_1.attributes.battery <= 60 %}
          mdi:battery-60
        {% elif states.sensor.hue_dimmer_switch_1.attributes.battery <= 70 %}
          mdi:battery-70
        {% elif states.sensor.hue_dimmer_switch_1.attributes.battery <= 80 %}
          mdi:battery-80
        {% elif states.sensor.hue_dimmer_switch_1.attributes.battery <= 90 %}
          mdi:battery-90
        {% else %}
          mdi:battery
        {% endif %}

    # Sum power
    total_power_livingroom:
      friendly_name: 'Living room power'
      value_template: '{{ ((states.sensor.volet_salon_power.attributes.power_consumption | float) + 
      (states.sensor.switch_home_cinema_power.attributes.power_consumption | float) +
      (states.sensor.livingroom_light_power.attributes.power_consumption | float)) }}'
      unit_of_measurement: 'W'
    total_power_desk:
      friendly_name: 'Desk power'
      value_template: '{{ ((states.sensor.volet_bureau_power.attributes.power_consumption | float)) }}'
      unit_of_measurement: 'W'
    total_power_home:
      friendly_name: 'Home power'
      value_template: '{{ ((states.sensor.total_power_livingroom.state | float) + 
      (states.sensor.total_power_desk.state | float)) }}'
      unit_of_measurement: 'W'
